sonar.projectKey=louisan-cicd-tasklist-backend
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

sonar.sources=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server.ts,**/*.config.ts
sonar.junit.reportPaths=reports/junit.xml
